FROM python:3.8

WORKDIR /app

COPY . /app

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "interface.controllers.main:app", "--host", "0.0.0.0", "--port", "8000"]
